baseURL = 'https://srmorita.xyz/'
languageCode = 'en-us'
title = '~/srmorita'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true
pluralizeListTitles = false

[params]
  description = "Blog personal y cajón de desastres.."
  author = "~/srmorita"

[menu]
[[menu.main]]
identifier = "inicio"
name = "Inicio"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 20

[[menu.main]]
identifier = "ahora"
name = "Ahora"
url = "/ahora"
weight = 30

[[menu.main]]
identifier = "enlaces"
name = "Enlaces"
url = "/enlaces"
weight = 40

[markup]
 [markup.goldmark.renderer]
  unsafe = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS"]
